-- Run this script in the Supabase SQL Editor to create the necessary table.

-- Drop existing tables to start fresh
DROP TABLE IF EXISTS public.payees CASCADE;
DROP TABLE IF EXISTS public.accounts CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

create table public.users (
  id text not null primary key,
  username text not null unique,
  password_hash text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.accounts (
  id uuid not null primary key, -- UUIDs are generated by Python backend currently, so no default
  user_id text not null,
  balance float8 not null default 0,
  account_number text unique,
  cvv text,
  expiry_date text,
  -- New fields for polymorphic account types
  account_type text default 'CARD', -- 'CARD', 'UPI', 'NET_BANKING', 'CRYPTO'
  upi_id text,
  ifsc text,
  bank_name text,
  wallet_address text,
  network text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes for performance
create index idx_accounts_user_id on public.accounts(user_id);
create index idx_accounts_account_number on public.accounts(account_number);

create table public.payees (
  id uuid not null primary key default gen_random_uuid(),
  user_id text not null,
  name text not null,
  account_type text not null,
  account_identifier text not null, -- Stores upi_id, account_number, or wallet_address
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index idx_payees_user_id on public.payees(user_id);

-- Enable Row Level Security (RLS) is recommended but optional for this demo
alter table public.accounts enable row level security;
alter table public.payees enable row level security;

-- Policy to allow all access (for demo purposes - REPLACE with proper auth policies/service role in production)
create policy "Enable all access for all users" on public.accounts for all using (true) with check (true);
create policy "Enable all access for all payees" on public.payees for all using (true) with check (true);

-- ==========================================
-- Insert Sample Accounts for testing
-- ==========================================
INSERT INTO public.accounts (id, user_id, balance, account_type, account_number, cvv, expiry_date, upi_id, ifsc, bank_name, wallet_address, network) VALUES
  ('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d', 'demo_user', 50000.00, 'CARD', '4111222233334444', '123', '12/28', NULL, NULL, NULL, NULL, NULL),
  ('b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e', 'demo_user', 15000.00, 'UPI', NULL, NULL, NULL, 'testuser@ybl', NULL, NULL, NULL, NULL),
  ('c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f', 'demo_user', 125000.00, 'NET_BANKING', '0000111122223333', NULL, NULL, NULL, 'HDFC0001234', 'HDFC Bank', NULL, NULL),
  ('d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a', 'demo_user', 8.5, 'CRYPTO', NULL, NULL, NULL, NULL, NULL, NULL, '0x742d35Cc6634C0532925a3b844Bc454e4438f44e', 'Ethereum'),
  ('e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b', 'demo_merchant', 10000.00, 'CARD', '5555666677778888', '456', '01/29', NULL, NULL, NULL, NULL, NULL),
  ('f6a7b8c9-d0e1-2f3a-4b5c-6d7e8f9a0b1c', 'demo_merchant', 5000.00, 'UPI', NULL, NULL, NULL, 'merchant@okicici', NULL, NULL, NULL, NULL);

-- ==========================================
-- Insert Sample Payees
-- ==========================================
INSERT INTO public.payees (user_id, name, account_type, account_identifier) VALUES
  ('demo_user', 'Amazon India', 'UPI', 'amazon@apl'),
  ('demo_user', 'Netflix Subscription', 'CARD', '5555666677778888'),
  ('demo_user', 'John Doe (Freelancer)', 'CRYPTO', '0x123f681646d4a755815f9cb19e1acc8565a0c2ac'),
  ('demo_user', 'Landlord Rent', 'NET_BANKING', '0000555566667777');
